In [ ]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

# import libraries

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')

In [ ]:
tips.head()

# create np-array

# 1. create 1D, 2D, 3D and 4D array using np.array()

In [13]:
import numpy as np

arr=np.array([1,2,3])
arr2=np.array([[10,20,30],
              [60,80,90]
              ]
             )
arr3=np.array([
    [11,21,31],
    [2,3,42],
    [13,23,33]
])
arr4=np.array([
    [20,30,40],
    [50,60,70],
    [1,2,3],
    [4,5,6]
])

print(arr,arr2,arr3,arr4)


[1 2 3] [[10 20 30]
 [60 80 90]] [[11 21 31]
 [ 2  3 42]
 [13 23 33]] [[20 30 40]
 [50 60 70]
 [ 1  2  3]
 [ 4  5  6]]


# create 1D, 2D, 3D and 4D array using arange() and reshape()

In [24]:
import numpy as np
array=np.arange(24)
array2=array.reshape(4,6)
array3=array.reshape(2,2,6)
array4=array.reshape(2,2,2,3)
print(array,array2,array3,array4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] [[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]] [[[[ 0  1  2]
   [ 3  4  5]]

  [[ 6  7  8]
   [ 9 10 11]]]


 [[[12 13 14]
   [15 16 17]]

  [[18 19 20]
   [21 22 23]]]]


# create array using ones and zeros

In [25]:
import numpy as np

arr = np.array([0, 1])

print(arr)

[0 1]


# using random

In [30]:
import numpy as np
arr =np.random.randint(10,20,45)
print(arr)

[15 17 11 16 14 19 12 13 11 15 16 12 11 16 19 10 18 15 10 11 19 17 13 10
 10 12 16 18 19 10 10 10 10 15 13 10 16 12 15 13 16 11 18 11 11]


# using linspace

In [31]:
import numpy as np
arr=np.linspace(0,100,25)
print(arr)

[  0.           4.16666667   8.33333333  12.5         16.66666667
  20.83333333  25.          29.16666667  33.33333333  37.5
  41.66666667  45.83333333  50.          54.16666667  58.33333333
  62.5         66.66666667  70.83333333  75.          79.16666667
  83.33333333  87.5         91.66666667  95.83333333 100.        ]


# create 1D array of tip from tips dataframe

In [35]:
import numpy as np
import pandas as pd
tips = pd.read_csv("/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv")

tips_array=tips["tip"].to_numpy()
print(tips_array)

[ 1.01  1.66  3.5   3.31  3.61  4.71  2.    3.12  1.96  3.23  1.71  5.
  1.57  3.    3.02  3.92  1.67  3.71  3.5   3.35  4.08  2.75  2.23  7.58
  3.18  2.34  2.    2.    4.3   3.    1.45  2.5   3.    2.45  3.27  3.6
  2.    3.07  2.31  5.    2.24  2.54  3.06  1.32  5.6   3.    5.    6.
  2.05  3.    2.5   2.6   5.2   1.56  4.34  3.51  3.    1.5   1.76  6.73
  3.21  2.    1.98  3.76  2.64  3.15  2.47  1.    2.01  2.09  1.97  3.
  3.14  5.    2.2   1.25  3.08  4.    3.    2.71  3.    3.4   1.83  5.
  2.03  5.17  2.    4.    5.85  3.    3.    3.5   1.    4.3   3.25  4.73
  4.    1.5   3.    1.5   2.5   3.    2.5   3.48  4.08  1.64  4.06  4.29
  3.76  4.    3.    1.    4.    2.55  4.    3.5   5.07  1.5   1.8   2.92
  2.31  1.68  2.5   2.    2.52  4.2   1.48  2.    2.    2.18  1.5   2.83
  1.5   2.    3.25  1.25  2.    2.    2.    2.75  3.5   6.7   5.    5.
  2.3   1.5   1.36  1.63  1.73  2.    2.5   2.    2.74  2.    2.    5.14
  5.    3.75  2.61  2.    3.5   2.5   2.    2.    3.    3.48  

# create 2D array of tip and total_bill form tips dataframe

In [39]:
import numpy as np
import pandas as pd
tips = pd.read_csv("/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv")
total_bill=tips[["total_bill"]].to_numpy()

print(total_bill)

[[16.99]
 [10.34]
 [21.01]
 [23.68]
 [24.59]
 [25.29]
 [ 8.77]
 [26.88]
 [15.04]
 [14.78]
 [10.27]
 [35.26]
 [15.42]
 [18.43]
 [14.83]
 [21.58]
 [10.33]
 [16.29]
 [16.97]
 [20.65]
 [17.92]
 [20.29]
 [15.77]
 [39.42]
 [19.82]
 [17.81]
 [13.37]
 [12.69]
 [21.7 ]
 [19.65]
 [ 9.55]
 [18.35]
 [15.06]
 [20.69]
 [17.78]
 [24.06]
 [16.31]
 [16.93]
 [18.69]
 [31.27]
 [16.04]
 [17.46]
 [13.94]
 [ 9.68]
 [30.4 ]
 [18.29]
 [22.23]
 [32.4 ]
 [28.55]
 [18.04]
 [12.54]
 [10.29]
 [34.81]
 [ 9.94]
 [25.56]
 [19.49]
 [38.01]
 [26.41]
 [11.24]
 [48.27]
 [20.29]
 [13.81]
 [11.02]
 [18.29]
 [17.59]
 [20.08]
 [16.45]
 [ 3.07]
 [20.23]
 [15.01]
 [12.02]
 [17.07]
 [26.86]
 [25.28]
 [14.73]
 [10.51]
 [17.92]
 [27.2 ]
 [22.76]
 [17.29]
 [19.44]
 [16.66]
 [10.07]
 [32.68]
 [15.98]
 [34.83]
 [13.03]
 [18.28]
 [24.71]
 [21.16]
 [28.97]
 [22.49]
 [ 5.75]
 [16.32]
 [22.75]
 [40.17]
 [27.28]
 [12.03]
 [21.01]
 [12.46]
 [11.35]
 [15.38]
 [44.3 ]
 [22.42]
 [20.92]
 [15.36]
 [20.49]
 [25.21]
 [18.24]
 [14.31]
 [14.  ]
 

# practice atleast 2 example for each using ndim, shape, size and itemsize

In [1]:
import numpy as np

arr=np.array([1,2,3])

arr2=np.array([[10,20,30],
              [60,80,90]])

arr3=np.array([
    [11,21,31],
    [2,3,42],
    [13,23,33]
])

arr4=np.array([
    [20,30,40],
    [50,60,70],
    [1,2,3],
    [4,5,6]
])

print("arr")
print(arr)

print("ndim:", arr.ndim)
print("shape:", arr.shape)
print("size:", arr.size)
print("itemsize:", arr.itemsize)

print("\narr2")
print(arr2)

print("ndim:", arr2.ndim)
print("shape:", arr2.shape)
print("size:", arr2.size)
print("itemsize:", arr2.itemsize)

print("\narr3")
print(arr3)

print("ndim:", arr3.ndim)
print("shape:", arr3.shape)
print("size:", arr3.size)
print("itemsize:", arr3.itemsize)

print("\narr4")
print(arr4)

print("ndim:", arr4.ndim)
print("shape:", arr4.shape)
print("size:", arr4.size)
print("itemsize:", arr4.itemsize)

arr
[1 2 3]
ndim: 1
shape: (3,)
size: 3
itemsize: 8

arr2
[[10 20 30]
 [60 80 90]]
ndim: 2
shape: (2, 3)
size: 6
itemsize: 8

arr3
[[11 21 31]
 [ 2  3 42]
 [13 23 33]]
ndim: 2
shape: (3, 3)
size: 9
itemsize: 8

arr4
[[20 30 40]
 [50 60 70]
 [ 1  2  3]
 [ 4  5  6]]
ndim: 2
shape: (4, 3)
size: 12
itemsize: 8


#  change data type and memory size of any np-array using astype()

In [2]:
arr = np.array([1, 2, 3])

arr2 = arr.astype(np.float32)

print(arr2)
print(arr2.dtype)
print (arr.itemsize)

[1. 2. 3.]
float32
8


# create 2 same dimensional array and do scalar and vector operations

In [7]:
import numpy as np
a=np.array([5,10,15])
b=np.array([20,25,30])
print(a-5)
print(b+5)
print(a+10)
print(a-6)

[ 0  5 10]
[25 30 35]
[15 20 25]
[-1  4  9]


# find minimun and maximum tip

In [8]:
import numpy as np

a = np.array([5, 10, 15])
b = np.array([20, 25, 30])

print(np.min(a))
print(np.max(a))
print(np.min(b))
print(np.max(b))

5
15
20
30


# find average total_bill and average tip

In [12]:
import pandas as pd

tips = pd.read_csv("/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv")

print("average total_bill:", tips["total_bill"].mean())
print("average tip:", tips["tip"].mean())

average total_bill: 19.78594262295082
average tip: 2.99827868852459


# find median total_bill

In [13]:
print("Median total_bill:", tips["total_bill"].median())


Median total_bill: 17.795


# find standard deviasion and variance of tip

In [14]:
print("Standard deviation of tip:", tips["tip"].std())
print("Variance of tip:", tips["tip"].var())

Standard deviation of tip: 1.3836381890011826
Variance of tip: 1.9144546380624725


# find log values of tip

In [15]:
import numpy as np
import pandas as pd

tips = pd.read_csv(
    "/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv"
)

tip = tips["tip"].to_numpy()

print("Tip array:")
print(tip)

print("\nLog values:")
print(np.log(tip))

Tip array:
[ 1.01  1.66  3.5   3.31  3.61  4.71  2.    3.12  1.96  3.23  1.71  5.
  1.57  3.    3.02  3.92  1.67  3.71  3.5   3.35  4.08  2.75  2.23  7.58
  3.18  2.34  2.    2.    4.3   3.    1.45  2.5   3.    2.45  3.27  3.6
  2.    3.07  2.31  5.    2.24  2.54  3.06  1.32  5.6   3.    5.    6.
  2.05  3.    2.5   2.6   5.2   1.56  4.34  3.51  3.    1.5   1.76  6.73
  3.21  2.    1.98  3.76  2.64  3.15  2.47  1.    2.01  2.09  1.97  3.
  3.14  5.    2.2   1.25  3.08  4.    3.    2.71  3.    3.4   1.83  5.
  2.03  5.17  2.    4.    5.85  3.    3.    3.5   1.    4.3   3.25  4.73
  4.    1.5   3.    1.5   2.5   3.    2.5   3.48  4.08  1.64  4.06  4.29
  3.76  4.    3.    1.    4.    2.55  4.    3.5   5.07  1.5   1.8   2.92
  2.31  1.68  2.5   2.    2.52  4.2   1.48  2.    2.    2.18  1.5   2.83
  1.5   2.    3.25  1.25  2.    2.    2.    2.75  3.5   6.7   5.    5.
  2.3   1.5   1.36  1.63  1.73  2.    2.5   2.    2.74  2.    2.    5.14
  5.    3.75  2.61  2.    3.5   2.5   2.    2.    3

# apply round, floor and ceil operation on tip array

In [16]:
print("Round:", np.round(tip))
print("Floor:", np.floor(tip))
print("Ceil:", np.ceil(tip))

Round: [ 1.  2.  4.  3.  4.  5.  2.  3.  2.  3.  2.  5.  2.  3.  3.  4.  2.  4.
  4.  3.  4.  3.  2.  8.  3.  2.  2.  2.  4.  3.  1.  2.  3.  2.  3.  4.
  2.  3.  2.  5.  2.  3.  3.  1.  6.  3.  5.  6.  2.  3.  2.  3.  5.  2.
  4.  4.  3.  2.  2.  7.  3.  2.  2.  4.  3.  3.  2.  1.  2.  2.  2.  3.
  3.  5.  2.  1.  3.  4.  3.  3.  3.  3.  2.  5.  2.  5.  2.  4.  6.  3.
  3.  4.  1.  4.  3.  5.  4.  2.  3.  2.  2.  3.  2.  3.  4.  2.  4.  4.
  4.  4.  3.  1.  4.  3.  4.  4.  5.  2.  2.  3.  2.  2.  2.  2.  3.  4.
  1.  2.  2.  2.  2.  3.  2.  2.  3.  1.  2.  2.  2.  3.  4.  7.  5.  5.
  2.  2.  1.  2.  2.  2.  2.  2.  3.  2.  2.  5.  5.  4.  3.  2.  4.  2.
  2.  2.  3.  3.  2.  4.  2.  2. 10.  3.  5.  3.  4.  3.  2.  2.  4.  4.
  4.  6.  4.  6.  3.  5.  4.  2.  4.  4.  2.  4.  3.  2.  4.  1.  2.  5.
  2.  2.  4.  2.  2.  2.  4.  3.  3.  3.  2.  2.  2.  5.  9.  2.  6.  1.
  3.  2.  1.  3.  2.  3.  2.  3.  2.  2.  2.  3.  3.  3.  2.  3.  3.  1.
  3.  1.  1.  1.  5.  6.  2.  2.  2.  3.]
Fl

# use 1D, 2D and 3D np-array, and apply indexing and slicing atleast 5 example for each (take example as your wish)

# stacking and spliting

# use hstack() and vstack()

In [22]:
c = np.vstack((a, b))

print(c)
d = np.hstack((a, b))

print(d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


# use hsplit() and vsplit()